name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Authenticate to Google Cloud
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Step 3: Configure Docker for Artifact Registry
    - name: Configure Docker for Google Artifact Registry
      run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

    # Step 4: Build and push Docker image to Artifact Registry
    - name: Build and push Docker image
      run: |
        weather-app=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPOSITORY }}/weather-app
        docker build -t $weather-app .
        docker push $weather-app

    # Step 5: Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy weather-app \
          --image=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPOSITORY }}/weather-app \
          --platform=managed \
          --region=${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
