name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Authenticate to Google Cloud using a service account key
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    # Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    # Configure Docker for Artifact Registry
    - name: Configure Docker for Google Artifact Registry
      run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

    - name: Set environment variables from GitHub Secrets
        run: |
          echo "URL=${{ secrets.URL }}" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "HOST=${{ secrets.HOST }}" >> $GITHUB_ENV
          
    # Build and push Docker image with environment variables
    - name: Build and push Docker image
      run: |
        IMAGE_NAME="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPOSITORY }}/weather-app"
        echo "Using image name: $IMAGE_NAME"
        docker build \
          --build-arg URL=${{ secrets.URL }} \
          --build-arg API_KEY=${{ secrets.API_KEY }} \
          --build-arg HOST=${{ secrets.HOST }} \
          -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    # Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy weather-app \
          --image=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPOSITORY }}/weather-app \
          --platform=managed \
          --region=${{ secrets.GCP_REGION }} \
          --allow-unauthenticated \
          --set-env-vars URL=${{ secrets.URL }},API_KEY=${{ secrets.API_KEY }},HOST=${{ secrets.HOST }}
